### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by k4zy** [kazy1991/OgpView#1]
```
Process: com.github.kazy1991.remee, PID: 7244
java.nio.charset.UnsupportedCharsetException: none
    at java.nio.charset.Charset.forName(Charset.java:568)
    at okhttp3.MediaType.charset(MediaType.java:111)
    at okhttp3.ResponseBody.charset(ResponseBody.java:182)
    at okhttp3.ResponseBody.string(ResponseBody.java:173)
    at com.github.kazy1991.ogpview.OgpView$2.onResponse(OgpView.java:80)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)

```

**Comment by k4zy** [comment]
fixed: https://github.com/kazy1991/OgpView/pull/3
